#!/usr/bin/python3

#  Start with the code in word count reducer, but remember
#   * this reducer is taking (wordtype, length)
#   * and is computing the average

import sys

#  Current key being processed, and accumulated count
current_word = None
current_sum = 0
current_count = 0

# The word just being read in
word = None

# input comes from STDIN
for line in sys.stdin:
    
    # remove leading and trailing whitespace
    line = line.strip()
    
    word, length = line.split('\t', 1)

    try:
        length = int(length)
    except ValueError:
        # length was not a number, so silently
        # ignore/discard this line
        continue

    if current_word == word:
        # Seeing the same key.  Just accumulate
        current_sum += length
        current_count += 1
    else:
        # Seeing either a new different key, or the first one
        if current_word:
            # Write result to STDOUT
            avg = float(current_sum) / current_count
            print('%s\t%s' % (current_word, avg))
        current_count = 1
        current_sum = length
        current_word = word

# STDIN stream is empty.  But output the last key and value
if current_count > 0:
    avg = float(current_sum) / current_count
    print('%s\t%s' % (current_word, avg))
