#!/usr/bin/python3

# Reducer input is (word, 1) but unlike Java, it is not guaranteed to see just one word
# But it will see all tuples for a word before it sees any tuples from the next word

import sys

#  Current key being processed, and accumulated count
current_word = None
current_count = 0

# The word just being read in
word = None

# input comes from STDIN
for line in sys.stdin:
    
    # remove leading and trailing whitespace
    line = line.strip()
    
    # Parse the input we got from mapper -- (word <tab> count)
    # Second argument to split is maximum number of splits
    word, count = line.split('\t', 1)

    # Convert count (currently a string) to int, but guard against bad data
    # DANGER!  Continue silently on bad data.
    
    try:
        count = int(count)
    except ValueError:
        # count was not a number, so silently
        # ignore/discard this line
        continue

    if current_word == word:
        # Seeing the same key.  Just accumulate
        current_count += count
    else:
        # Seeing either a new different key, or the first one
        if current_word:
            # Write result to STDOUT
            print('%s\t%s' % (current_word, current_count))
        current_count = 1
        current_word = word

# STDIN stream is empty.  But output the last key and value
if current_count > 0:
    print('%s\t%s' % (current_word, current_count))
