#!/usr/bin/python3

import sys

# input comes from STDIN (standard input)
for line in sys.stdin:
    # remove leading and trailing whitespace
    line = line.strip()
    # split the line into words
    words = line.split()
    for word in words:
        # Convert to lower case, then remove all non-letters
        lowered = word.lower()
        filtered = "".join(filter(lambda c: 97 <= ord(c) <= 122, lowered))
        # Emit a key/value pair only if the key is not empty
        if len(filtered) > 0:
            # Output is a tab-delimited string
            print('%s\t%s' % (filtered, 1))
